package org.apache.jsp.jsp.kochbuch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.hbedv.kochbuch.*;
import com.hbedv.frame.*;
import com.hbedv.db.kochbuch.KochbuchBean;

public final class edit_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static java.util.List _jspx_dependants;

  static {
    _jspx_dependants = new java.util.ArrayList(7);
    _jspx_dependants.add("/jsp/kochbuch/import.jsp");
    _jspx_dependants.add("/jsp/kochbuch/header.jsp");
    _jspx_dependants.add("/jsp/kochbuch/js.jsp");
    _jspx_dependants.add("/jsp/kochbuch/zutaten.jsp");
    _jspx_dependants.add("/jsp/kochbuch/kommentar.jsp");
    _jspx_dependants.add("/jsp/kochbuch/zubereitung.jsp");
    _jspx_dependants.add("/jsp/kochbuch/footer.jsp");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.AnnotationProcessor _jsp_annotationprocessor;

  public Object getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = JspFactory.getDefaultFactory().getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_annotationprocessor = (org.apache.AnnotationProcessor) getServletConfig().getServletContext().getAttribute(org.apache.AnnotationProcessor.class.getName());
  }

  public void _jspDestroy() {
  }

  public void _jspService(HttpServletRequest request, HttpServletResponse response)
        throws java.io.IOException, ServletException {

    JspFactory _jspxFactory = null;
    PageContext pageContext = null;
    HttpSession session = null;
    ServletContext application = null;
    ServletConfig config = null;
    JspWriter out = null;
    Object page = this;
    JspWriter _jspx_out = null;
    PageContext _jspx_page_context = null;


    try {
      _jspxFactory = JspFactory.getDefaultFactory();
      response.setContentType("text/html; charset=iso-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"../errorpage.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 
	ClientKochbuch client= (ClientKochbuch)request.getAttribute("com.hbedv.client");
	KochbuchManager manager = (KochbuchManager) client.getManager();
	client.setUpLoadPic(manager.getPicFileName());
	manager.readMenueList();
	AliceSortMap menueListe = manager.getAsmMenueListe();
	String auswahlErr = "";

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.print(client.getUriCssGlobal("kochbuch.css"));
      out.write("\" type=\"text/css\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\">\r\n");
      out.write("<title>Kochbuch</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("isIE10=\"IE10\";\r\n");
      out.write("isIE11=\"IE11\"; \r\n");
      out.write("isFireFox=\"FireFox\";\r\n");
      out.write("isEdge=\"Edge\";\r\n");
      out.write("isOpera=\"Opera\";\r\n");
      out.write("isChrome=\"Chrome\";\r\n");
      out.write("isSafari=\"Safari\";\r\n");
      out.write("isUnknown=\"Unknown\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function getBrowserName() {\r\n");
      out.write("\r\n");
      out.write("\tvar ret=isUnknown;\r\n");
      out.write("\r\n");
      out.write("\tif((navigator.userAgent.indexOf(\"Opera\") || navigator.userAgent.indexOf('OPR')) != -1 ) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isOpera;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(navigator.userAgent.indexOf(\"Chrome\") != -1 )\r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isChrome;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(navigator.userAgent.indexOf(\"Safari\") != -1)\r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isSafari;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if(navigator.userAgent.indexOf(\"Firefox\") != -1 ) \r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isFireFox;\r\n");
      out.write("\t}\r\n");
      out.write("\telse if((navigator.userAgent.indexOf(\"MSIE\") != -1 ) || (document.documentMode == true )) //IF IE < 11\r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isIE10; \r\n");
      out.write("\t}\r\n");
      out.write("\telse if((navigator.userAgent.indexOf(\"MSIE\") != -1 ) || (!!document.documentMode == true )) //IF IE > 10\r\n");
      out.write("\t{\r\n");
      out.write("\t\tret=isIE11; \r\n");
      out.write("\t}  \r\n");
      out.write("\t \r\n");
      out.write("\telse if (navigator.userAgent.indexOf(\"Edge\") > -1) {\r\n");
      out.write("\t\tret=isEdge;\r\n");
      out.write("\t}\r\n");
      out.write("\treturn ret;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write("function ResizeApp() {\r\n");
      out.write("\r\n");
      out.write("\tvar outerWidth = window.outerWidth;  \r\n");
      out.write("\tvar outerHeight = window.outerHeight;\r\n");
      out.write("\r\n");
      out.write("\tbsWidth = document.getElementById('bs_width');\r\n");
      out.write("\tif (bsWidth != null) {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tbsWidth.value = outerWidth;\r\n");
      out.write("\r\n");
      out.write("\t\tbsHeight = document.getElementById('bs_height');\r\n");
      out.write("\t\tif (bsHeight != null) {\r\n");
      out.write("\t\t\tbsHeight.value = outerHeight; \r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tobjTxt1 = document.getElementById('text_width');\r\n");
      out.write("\t\tif (objTxt1 != null) {\r\n");
      out.write("\t\t\tobjTxt1.value = document.getElementById('bs_width').value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tobjTxt2 = document.getElementById('text_height');\r\n");
      out.write("\t\tif (objTxt2 != null) {\r\n");
      out.write("\t\t\tobjTxt2.value = document.getElementById('bs_height').value;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tif (typeof ResizeWindow === \"function\") {\r\n");
      out.write("\t\tResizeWindow(outerWidth,outerHeight);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("window.addEventListener('resize', ResizeApp);\r\n");
      out.write("</script\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<BODY BGCOLOR=#ECE3BE LEFTMARGIN=0 TOPMARGIN=0 MARGINWIDTH=0 MARGINHEIGHT=0>\r\n");
      out.write("\r\n");
      out.write("<form name=\"BodyForm\" method=\"post\" action=\"");
      out.print(TheApp.encodeURL(client.getUriForm(), response));
      out.write("\" target=\"body\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"bs_width\" name=\"bs_width\" value=\"0\">\r\n");
      out.write("<input type=\"hidden\" id=\"bs_height\" name=\"bs_height\" value=\"0\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" id=\"text_width\" name=\"text_width\" >\r\n");
      out.write("<input type=\"hidden\" id=\"text_height\" name=\"text_height\">\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"cmd\" value=\"\">\r\n");
      out.write("<input type=\"hidden\" name=\"subcmd\" value=\"\">\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(client.getUriJSGlobal("eventhandler.js"));
      out.write("\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(client.getUriJSGlobal("basic.js"));
      out.write("\"></script>\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("\r\n");
      out.write("setDefaultButton(\"saveButton\");\r\n");
      out.write("\r\n");

if (client.getMessage() != null && !client.getMessage().equals("")) { 
      out.write("\r\n");
      out.write("\talert(\"");
      out.print(client.getMessage());
      out.write("\");\r\n");
      out.write("\t");

	client.setMessage("");
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("function zurueckZurAuswahl(f) {\r\n");
      out.write("\tf.cmd.value=\"");
      out.print(TheApp.CMD_SEARCH);
      out.write("\";\r\n");
      out.write("\tf.subcmd.value=\"");
      out.print(TheApp.SUB_CMD_INIT);
      out.write("\";\r\n");
      out.write("\tf.submit();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function saveRezept(f) {\r\n");
      out.write("\tvar rez = f.rezeptname.value;\r\n");
      out.write("\trez = ba_allTrim(rez);\r\n");
      out.write("\tif (rez == \"\") {\r\n");
      out.write("\t\talert(\"Rezeptname darf nicht leer sein!\");\r\n");
      out.write("\t\tf.rezeptname.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse if (f.m_id.value == 0) {\r\n");
      out.write("\t\talert(\"");
      out.print(auswahlErr);
      out.write("\");\r\n");
      out.write("\t\tf.selectMenues.focus();\r\n");
      out.write("\t}\r\n");
      out.write("\telse {\r\n");
      out.write("\t\tf.cmd.value=\"");
      out.print(TheApp.CMD_SEARCH);
      out.write("\";\r\n");
      out.write("\t\tf.subcmd.value=\"");
      out.print(Kochbuch.SUB_CMD_SAVE);
      out.write("\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function changeMenue(f,wert) {\r\n");
      out.write("\tf.m_id.value = wert;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function picDelete(f) {\r\n");
      out.write("\tvar lOk = confirm(\"Bild entfernen ?\");\r\n");
      out.write("\tif (lOk) {\r\n");
      out.write("\t\tf.cmd.value=\"");
      out.print(TheApp.CMD_SEARCH);
      out.write("\";\r\n");
      out.write("\t\tf.subcmd.value=\"");
      out.print(Kochbuch.SUB_CMD_DELETE_PIC);
      out.write("\";\r\n");
      out.write("\t\tf.submit();\r\n");
      out.write("\t} \r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function picUpload(f) {\r\n");
      out.write("\twin2 = \twindow.open(\"\",\"\",\"toolbar=no,location=no,\"+\r\n");
      out.write("  \t \t\t\"directories=no,status=yes,menubar=no,scrollbars=no,resizable=no,\"+\r\n");
      out.write("  \t\t\t\"copyhistory=no\");\r\n");
      out.write("\twin2.resizeTo(700,300);\r\n");
      out.write("\twin2.location.href=\"");
      out.print(client.getAppRootUrl());
      out.write("/jsp/upload.jsp\";\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function insertCode(aTag, eTag, nameForm, nameTArea) {\r\n");
      out.write("  var input = document.forms[nameForm].elements[nameTArea];\r\n");
      out.write("  input.focus();\r\n");
      out.write("  /* für Internet Explorer */\r\n");
      out.write("  if(typeof document.selection != 'undefined') {\r\n");
      out.write("    /* Einfügen des Formatierungscodes */\r\n");
      out.write("    var range = document.selection.createRange();\r\n");
      out.write("    var insText = range.text;\r\n");
      out.write("    range.text = aTag + insText + eTag;\r\n");
      out.write("    /* Anpassen der Cursorposition */\r\n");
      out.write("    range = document.selection.createRange();\r\n");
      out.write("    if (insText.length == 0) {\r\n");
      out.write("      range.move('character', -eTag.length);\r\n");
      out.write("    } else {\r\n");
      out.write("      range.moveStart('character', aTag.length + insText.length + eTag.length);      \r\n");
      out.write("    }\r\n");
      out.write("    range.select();\r\n");
      out.write("  }\r\n");
      out.write("  /* für neuere auf Gecko basierende Browser */\r\n");
      out.write("  else if(typeof input.selectionStart != 'undefined')\r\n");
      out.write("  {\r\n");
      out.write("    /* Einfügen des Formatierungscodes */\r\n");
      out.write("    var start = input.selectionStart;\r\n");
      out.write("    var end = input.selectionEnd;\r\n");
      out.write("    var insText = input.value.substring(start, end);\r\n");
      out.write("    input.value = input.value.substr(0, start) + aTag + insText + eTag + input.value.substr(end);\r\n");
      out.write("    /* Anpassen der Cursorposition */\r\n");
      out.write("    var pos;\r\n");
      out.write("    if (insText.length == 0) {\r\n");
      out.write("      pos = start + aTag.length;\r\n");
      out.write("    } else {\r\n");
      out.write("      pos = start + aTag.length + insText.length + eTag.length;\r\n");
      out.write("    }\r\n");
      out.write("    input.selectionStart = pos;\r\n");
      out.write("    input.selectionEnd = pos;\r\n");
      out.write("  }\r\n");
      out.write("  /* für die übrigen Browser */\r\n");
      out.write("  else\r\n");
      out.write("  {\r\n");
      out.write("    /* Abfrage der Einfügeposition */\r\n");
      out.write("    var pos;\r\n");
      out.write("    var re = new RegExp('^[0-9]{0,3}$');\r\n");
      out.write("    while(!re.test(pos)) {\r\n");
      out.write("      pos = prompt(\"Einfügen an Position (0..\" + input.value.length + \"):\", \"0\");\r\n");
      out.write("    }\r\n");
      out.write("    if(pos > input.value.length) {\r\n");
      out.write("      pos = input.value.length;\r\n");
      out.write("    }\r\n");
      out.write("    /* Einfügen des Formatierungscodes */\r\n");
      out.write("    var insText = prompt(\"Bitte geben Sie den zu formatierenden Text ein:\");\r\n");
      out.write("    input.value = input.value.substr(0, pos) + aTag + insText + eTag + input.value.substr(pos);\r\n");
      out.write("  }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("function ResizeWindow(outerWidth,outerHeight) {\r\n");
      out.write("\t//alert (\"OK\");\r\n");
      out.write("\tvar innerWidth = window.innerWidth;  \r\n");
      out.write("\tvar innerHeight = window.innerHeight;\r\n");
      out.write("\t\r\n");
      out.write("\tvar speisenTyp = document.getElementById('speisenTyp');\r\n");
      out.write("\tvar rect = speisenTyp.getBoundingClientRect();\r\n");
      out.write("\t//alert(rect.width);\r\n");
      out.write("\tif (rect.width < 400) {\r\n");
      out.write("\t\tspeisenTyp.style.width = '400px';\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tvar table01 = document.getElementById('table01');\r\n");
      out.write("\ttable01.style.position = \"absolute\";\r\n");
      out.write("\ttable01.style.top = '30px';\r\n");
      out.write("\ttable01.style.left = '30px';\r\n");
      out.write("\t\r\n");
      out.write("\tvar wi = innerWidth-60;\r\n");
      out.write("\ttable01.style.width = wi+'px';\r\n");
      out.write("\t\r\n");
      out.write("\tvar wi = innerHeight-30;\r\n");
      out.write("\ttable01.style.height = wi+'px';\r\n");
      out.write("\t\r\n");
      out.write("\tif (typeof includeScriptZutaten === \"function\") {\r\n");
      out.write("\t\tincludeScriptZutaten(outerWidth,outerHeight,innerWidth,innerHeight,'table02');\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (typeof includeScriptKommentar === \"function\") {\r\n");
      out.write("\t\tincludeScriptKommentar(outerWidth,outerHeight,innerWidth,innerHeight);\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write("\tif (typeof includeScriptZubereitung === \"function\") {\r\n");
      out.write("\t\tincludeScriptZubereitung(outerWidth,outerHeight,innerWidth,innerHeight);\r\n");
      out.write("\t}\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<input type=\"hidden\" name=\"m_id\" value=\"");
      out.print(manager.getMenId());
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"r_id\" value=\"");
      out.print(manager.getRezId());
      out.write("\">\r\n");
      out.write("<input type=\"hidden\" name=\"lastMenId\" value=\"");
      out.print(manager.getMenId());
      out.write("\">\r\n");
      out.write("\r\n");
      out.write("<table id=\"table01\" width=\"100%\" border=\"0\" >\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td width=\"50%\" align=\"left\" valign=\"middle\">\r\n");
      out.write("\t\t\t<p>\r\n");
      out.write("\t\t\t\tRezeptname:&nbsp;\r\n");
      out.write("\t\t\t\t<font size=\"5\" face=\"Sylfaen\">\r\n");
      out.write("\t\t\t\t\t<strong>");
      out.print(manager.getRezeptNameJSP());
      out.write("</strong>\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t<input type=\"hidden\" name=\"rezeptname\" value=\"");
      out.print(manager.getRezeptName());
      out.write("\">\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td width=\"50%\" align=\"left\" valign=\"middle\" style=\"height:30px;\">\r\n");
      out.write("\t\t\t<p id=\"speisenTyp\">Typ&nbsp;der&nbsp;Speise:&nbsp;\r\n");
      out.write("\t\t\t\t<select size=\"1\" name=\"selectMenues\" class=\"kb\" style=\"width:186px;\" onChange=\"changeMenue(BodyForm,this.value)\">\r\n");
      out.write("\t\t\t\t\t");

					String selected = "";
					Integer aktId = manager.getMenId();
					for (int index=0;index<menueListe.getSize();index++) {
						String bez = (String) menueListe.getKeys(KochbuchBean.AsmMenue.KEY_BEZ).get(index);	
						Integer id = (Integer) menueListe.getKeys(KochbuchBean.AsmMenue.KEY_ID).get(index);	
						if (aktId.equals(id)) {
							selected = "selected";
						}
						else {
							selected = "";
						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<option ");
      out.print(selected);
      out.write(" value=");
      out.print(id);
      out.write('>');
      out.print(bez);
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t</select>\r\n");
      out.write("\t\t\t</p>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td align=\"left\"  valign=\"top\">\r\n");
      out.write("\t\t\t<table id=\"table02\" border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:50%\">\r\n");
      out.write("\t\t\t\t\t\t");

AliceSortMap zutatenListe = manager.getZutaten();

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("var aktuelleZeile = 1;\r\n");
      out.write("\r\n");
      out.write("function setZutatenZeile(zeile) {\r\n");
      out.write("\taktuelleZeile = zeile;\r\n");
      out.write("}\r\n");
      out.write("function insertZutat(f) {\r\n");
      out.write("\tfor (index=98;index>=aktuelleZeile;index--) {\r\n");
      out.write("\t\tvar wertAnzahl = eval(f.name + \".anzahl_\" + index + \".value\");\r\n");
      out.write("\t\tvar wertEinheit = eval(f.name + \".einheit_\" + index + \".value\");\r\n");
      out.write("\t\tvar wertZutat = eval(f.name + \".zutaten_\" + index + \".value\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\teval(f.name + \".anzahl_\" + (index + 1) + \".value = '\" + wertAnzahl + \"';\");\r\n");
      out.write("\t\teval(f.name + \".einheit_\" + (index + 1) + \".value = '\" + wertEinheit + \"';\");\r\n");
      out.write("\t\teval(f.name + \".zutaten_\" + (index + 1) + \".value = '\" + wertZutat + \"';\");\r\n");
      out.write("\t}\r\n");
      out.write("\teval(f.name + \".anzahl_\" + aktuelleZeile + \".value = '';\");\r\n");
      out.write("\teval(f.name + \".einheit_\" + aktuelleZeile + \".value = '';\");\r\n");
      out.write("\teval(f.name + \".zutaten_\" + aktuelleZeile + \".value = '';\");\r\n");
      out.write("\teval(f.name + \".anzahl_\" + aktuelleZeile + \".focus();\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function deleteZutat(f) {\r\n");
      out.write("\tfor (index=aktuelleZeile;index<99;index++) {\r\n");
      out.write("\t\tvar wertAnzahl = eval(f.name + \".anzahl_\" + (index + 1) + \".value\");\r\n");
      out.write("\t\tvar wertEinheit = eval(f.name + \".einheit_\" + (index + 1) + \".value\");\r\n");
      out.write("\t\tvar wertZutat = eval(f.name + \".zutaten_\" + (index + 1) + \".value\");\r\n");
      out.write("\t\t\r\n");
      out.write("\t\teval(f.name + \".anzahl_\" + index + \".value = '\" + wertAnzahl + \"';\");\r\n");
      out.write("\t\teval(f.name + \".einheit_\" + index + \".value = '\" + wertEinheit + \"';\");\r\n");
      out.write("\t\teval(f.name + \".zutaten_\" + index + \".value = '\" + wertZutat + \"';\");\r\n");
      out.write("\t} \r\n");
      out.write("\tf.anzahl_99.value = '';\r\n");
      out.write("\tf.einheit_99.value = '';\r\n");
      out.write("\tf.zutaten_99.value = '';\r\n");
      out.write("\teval(f.name + \".anzahl_\" + aktuelleZeile + \".focus();\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("function includeScriptZutaten(outerWidth,outerHeight,innerWidth,innerHeight,id1) {\r\n");
      out.write("\tvar divZut01 = document.getElementById('divZut01');\r\n");
      out.write("\tvar e = (outerHeight/2) - 240;\r\n");
      out.write("\tdivZut01.style.height = e + \"px\";\r\n");
      out.write("\r\n");
      out.write("\tvar e = (innerWidth/2) - 60;\r\n");
      out.write("\tvar divZu = e;\r\n");
      out.write("\tif (e > 352) divZut01.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar table03 = document.getElementById('table03');\r\n");
      out.write("\tvar e = (innerWidth/2) - 90;\r\n");
      out.write("\tif (e > 260) table03.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar zut_Td_01 = document.getElementById('zut_Td_01');\r\n");
      out.write("\tvar e = (innerWidth/2) - 60;\r\n");
      out.write("\tif (e > 260) zut_Td_01.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar th01 = document.getElementById('th01');\r\n");
      out.write("\tvar e = (innerWidth/2) - 220;\r\n");
      out.write("\tif (e > 200) th01.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\tvar th02 = document.getElementById('th02');\r\n");
      out.write("\tvar e = (divZu/5);\r\n");
      out.write("\tth02.style.width = e + \"px\";\r\n");
      out.write("\t\t\r\n");
      out.write("\tvar th03 = document.getElementById('th03');\r\n");
      out.write("\tvar e = (divZu/5) * 4;\r\n");
      out.write("\tif (e > 460) th03.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\t");

	for (int index=0;index<zutatenListe.getSize();index++) {
		
      out.write("\r\n");
      out.write("\t\tvar inptxt");
      out.print(index);
      out.write(" = document.getElementById('inptxt");
      out.print(index);
      out.write("');\r\n");
      out.write("\t\tvar e = (innerWidth/2) - 220;\r\n");
      out.write("\t\tif (e > 200) inptxt");
      out.print(index);
      out.write(".style.width = e + \"px\";\r\n");
      out.write("\t\t");

	}
	int startJS = zutatenListe.getSize();
	for (int index=startJS;index<100;index++) {
		
      out.write("\r\n");
      out.write("\t\tvar inptxt");
      out.print(index);
      out.write(" = document.getElementById('inptxt");
      out.print(index);
      out.write("');\r\n");
      out.write("\t\tvar e = (innerWidth/2) - 220;\r\n");
      out.write("\t\tif (e > 200) inptxt");
      out.print(index);
      out.write(".style.width = e + \"px\";\r\n");
      out.write("\t\t");

	}
	
      out.write("\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td>\r\n");
      out.write("\t\t\t\t<table>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t<td id=\"th02\">\r\n");
      out.write("\t\t\t\t\t\t\t<font size=\"5\" face=\"Sylfaen\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<strong>\r\n");
      out.write("\t\t\t\t\t\t\t\t\tZutaten\r\n");
      out.write("\t\t\t\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t<td  id=\"th03\" style=\"text-align:right;\">\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton2\" accesskey=\"e\" style=\"width:120px;\" name=\"bZutatInsert\" \r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Zutat einf&uuml;gen\" onClick=\"javascript:insertZutat(document.BodyForm);\" >\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton2\" accesskey=\"l\" style=\"width:120px;\" name=\"bZutatDelete\" \r\n");
      out.write("\t\t\t\t\t\t\tvalue=\"Zutat l&ouml;schen\" onClick=\"javascript:deleteZutat(document.BodyForm);\" >\r\n");
      out.write("\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t</table>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td id=\"zut_Td_01\">\r\n");
      out.write("\t\t\t\t<div id=\"divZut01\" align=\"left\" style=\"overflow:auto;border-color:#D9B565; border-width:1px;border-style:solid;padding:2px;\">\r\n");
      out.write("\t\t\t\t\t<table id=\"table03\" border=\"0\">\r\n");
      out.write("\t\t\t\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align:center;\">Anzahl</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th style=\"text-align:left\" >Einheit</th>\r\n");
      out.write("\t\t\t\t\t\t\t<th id=\"th01\" style=\"text-align:left;\">Zutaten</th>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						for (int index=0;index<zutatenListe.getSize();index++) {
							String anzStr = (String) zutatenListe.getKeys(KochbuchBean.AsmZutaten.KEY_ANZAHL).get(index);
							String einheit = (String) zutatenListe.getKeys(KochbuchBean.AsmZutaten.KEY_EINHEIT).get(index);
							String zutaten = (String) zutatenListe.getKeys(KochbuchBean.AsmZutaten.KEY_BEZ).get(index);
							
      out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" name=\"anzahl_");
      out.print(index);
      out.write("\" value=\"");
      out.print(anzStr);
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tonBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" style=\"width:50px;text-align:center;\" class=\"kbedit\"  >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td style=\"width:50px;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" name=\"einheit_");
      out.print(index);
      out.write("\" value=\"");
      out.print(einheit);
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tonBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" style=\"width:50px\" class=\"kbedit\">\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"inptxt");
      out.print(index);
      out.write("\" type=\"text\" maxlength=\"50\" size=\"50\" name=\"zutaten_");
      out.print(index);
      out.write("\" value=\"");
      out.print(zutaten);
      out.write("\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tonBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" class=\"kbedit\">\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t\t");

						}
						
						int start = zutatenListe.getSize();
						for (int index=start;index<100;index++) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" name=\"anzahl_");
      out.print(index);
      out.write("\" value=\"\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width:50px;text-align:center;\" onBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" class=\"kbedit\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"text\" maxlength=\"10\" name=\"einheit_");
      out.print(index);
      out.write("\" value=\"\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tstyle=\"width:50px;\" onBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" class=\"kbedit\" >\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input id=\"inptxt");
      out.print(index);
      out.write("\" type=\"text\" maxlength=\"50\" size=\"50\" name=\"zutaten_");
      out.print(index);
      out.write("\" value=\"\" \r\n");
      out.write("\t\t\t\t\t\t\t\t\tonBlur=\"setZutatenZeile(");
      out.print(index);
      out.write(")\" class=\"kbedit\" >\t\r\n");
      out.write("\t\t\t\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t\t");

						}
						
      out.write("\r\n");
      out.write("\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\t\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td style=\"width:50%\">\r\n");
      out.write("\t\t\t\t\t\t");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("function includeScriptKommentar(outerWidth,outerHeight,innerWidth,innerHeight) {\r\n");
      out.write("\t\r\n");
      out.write("\tvar kommentarId = document.getElementById('kommentarId');\r\n");
      out.write("\tvar e = (innerWidth/2)-276;\r\n");
      out.write("\t//alert(e); //730\r\n");
      out.write("\tif (e > 136) kommentarId.style.width = e + \"px\";\r\n");
      out.write("\t\r\n");
      out.write("\t//kommentarId.style.position = \"relative\";\r\n");
      out.write("\t//kommentarId.style.left = \"-6px\";\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<table>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<table>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t\t<font size=\"5\" face=\"Sylfaen\">\r\n");
      out.write("\t\t\t\t\t\t\t<strong>\r\n");
      out.write("\t\t\t\t\t\t\t\tKommentar\r\n");
      out.write("\t\t\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t<tr valign=\"top\">\r\n");
      out.write("\t\t\t\t\t<td height=\"100%\" align=\"center\">\r\n");
      out.write("\t\t\t\t\t\t<textarea id=\"kommentarId\" name=\"kommentar\" rows=\"8\" class=\"kb\" wrap=\"hard\">");
      out.print(manager.getKommentar());
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\t\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td>\r\n");
      out.write("\t\t\t<img name=\"meinRezept\" src=\"");
      out.print(manager.getPicName());
      out.write("\" width=\"200px\" height=\"180px\" ALT=\"\"  style=\"position:relative;top:10px;\">\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t\t<td valign=\"top\">\r\n");
      out.write("\t\t\t");
      out.write("<script language=\"JavaScript\" type=\"text/JavaScript\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("function includeScriptZubereitung(outerWidth,outerHeight,innerWidth,innerHeight) {\r\n");
      out.write("\r\n");
      out.write("\tvar zubTable01 = document.getElementById('zubTable01');\r\n");
      out.write("\tzubTable01.style.position = \"absolute\";\r\n");
      out.write("\tzubTable01.style.top = '72px';\r\n");
      out.write("\t\r\n");
      out.write("\tvar e = (innerWidth/2) - 30;\r\n");
      out.write("\tzubTable01.style.width =  e + 'px';\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("\tvar divZut01 = document.getElementById('divZut01');\r\n");
      out.write("\tif (divZut01 != null) {\r\n");
      out.write("\t\tvar rect = divZut01.getBoundingClientRect();\r\n");
      out.write("\t\te = rect.height + 214;\r\n");
      out.write("\t\tvar zubText01 = document.getElementById('zubText01');\r\n");
      out.write("\t\tzubText01.style.height = e + 'px';\r\n");
      out.write("\t}\r\n");
      out.write("}\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<table id = \"zubTable01\" width=\"100%\">\r\n");
      out.write("\t\t<tr>\r\n");
      out.write("\t\t\t<td width=\"50%\">\r\n");
      out.write("\t\t\t\t<font size=\"5\" face=\"Sylfaen\">\r\n");
      out.write("\t\t\t\t\t<strong>\r\n");
      out.write("\t\t\t\t\t\tZubereitung\r\n");
      out.write("\t\t\t\t\t</strong>\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t\t<td width=\"50%\" align=\"right\">\r\n");
      out.write("\t\t\t\t<input class=\"kbbutton2\" type=\"button\" value=\"Fett\" accesskey=\"f\" style=\"width:60px;\" \r\n");
      out.write("\t\t\t\t\tonClick=\"insertCode('<b>', '</b>','BodyForm','zubereitung')\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<input class=\"kbbutton2\" type=\"button\" value=\"Kursiv\" accesskey=\"k\" style=\"width:60px;\" \r\n");
      out.write("\t\t\t\t\tonClick=\"insertCode('<em>', '</em>','BodyForm','zubereitung')\">\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t\t<tr valign=\"top\" align=\"center\">\r\n");
      out.write("\t\t\t<td colspan=\"2\" width=\"100%\">\t\t\r\n");
      out.write("\t\t\t\t<textarea id=\"zubText01\" name =\"zubereitung\" cols=\"58\" rows=\"20\" class=\"kb\" wrap=\"hard\" style=\"width:98%\">");
      out.print(manager.getZubereitung());
      out.write("</textarea>\r\n");
      out.write("\t\t\t</td>\r\n");
      out.write("\t\t</tr>\r\n");
      out.write("\t</table>\r\n");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("\t<tr>\r\n");
      out.write("\t\t<td id = \"buttonTd\" align=\"center\" colspan=\"2\" height=\"100%\" valign=\"middle\" style=\"position:relative;top:-6px;\">\r\n");
      out.write("\t\t\t<table border=\"0\">\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" width=\"128px\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton2\" style=\"width:120px;\" name=\"upLoadButton\" value=\"Bild hochladen\" onClick=\"javascript:picUpload(BodyForm)\" >\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" width=\"128px\">\r\n");
      out.write("\t\t\t\t\t\t");

						String vgl = client.getAppRootUrl() + "/images/data/nopic.jpg";
						String bild = manager.getPicName();
						if (!bild.equalsIgnoreCase(vgl)) { 
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton2\" style=\"width:120px;\" name=\"deleteButton\" value=\"Bild l&ouml;schen\" onClick=\"javascript:picDelete(BodyForm)\" >\r\n");
      out.write("\t\t\t\t\t\t");
 } 
      out.write("\r\n");
      out.write("\t\t\t\t\t<td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" width=\"128px\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton\" style=\"width:120px;\" id=\"saveButton\" name=\"saveButton\" value=\"Speichern\" onClick=\"javascript:saveRezept(BodyForm)\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t\t<td align=\"left\" width=\"128px\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"button\" class=\"kbbutton2\" style=\"width:120px\" name=\"zurueckButton\" value=\"Zur&uuml;ck\" onClick=\"javascript:zurueckZurAuswahl(BodyForm)\" >\r\n");
      out.write("\t\t\t\t\t</td>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</table>\r\n");
      out.write("\t\t</td>\r\n");
      out.write("\t</tr>\r\n");
      out.write("</table>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\" language=\"javascript\">\r\n");
      out.write("\r\n");
      out.write("if (typeof ResizeApp === \"function\") {\r\n");
      out.write("\t\tResizeApp();\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</BODY>\r\n");
      out.write("</HTML>\r\n");
      out.write("\r\n");
      out.write('\r');
      out.write('\n');
    } catch (Throwable t) {
      if (!(t instanceof SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
      }
    } finally {
      if (_jspxFactory != null) _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
